project:
  type: website
  output-dir: docs

website:
  title: "Bipolar Risk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - whitepaper.qmd
      - posts.qmd
      - resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



